///////////////////////////////////////////////////////////////////////////////
//                           !! AUTO-GENERATED FILE !!                       //
//  This file has been automatically generated by generate_gql_types.ts. It  //
// is highly recommended that this file is not edited; instead, extend the   //
// given class into a new class.                                             //
///////////////////////////////////////////////////////////////////////////////

import { Field, ID, Int, InputType } from "type-graphql";
import { Arc } from "../../../entities/Arc";
  

@InputType()
export class ArcGeneratedInput implements Partial<Arc> {

  @Field( () => ID, {"nullable":true} )
  _id?: string;

  @Field( {"nullable":true} )
  title?: string;

  @Field( {"nullable":true} )
  description?: string;

  @Field( _type => Int, {"nullable":true} )
  order?: number;

  @Field( {"nullable":true} )
  storyID?: string;

  @Field( _type => Int, {"nullable":true} )
  words?: number;

  @Field( _type => Int, {"nullable":true} )
  rewindWords?: number;

}
